# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{forgery}
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nathan Sutton"]
  s.date = %q{2009-11-13}
  s.description = %q{Easy and customizable generation of forged data. Can be used as a gem or a rails plugin. Includes rails generators for creating your own forgeries.}
  s.email = %q{nate@sevenwire.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION.yml",
     "forgery.gemspec",
     "generators/forgery/USAGE",
     "generators/forgery/forgery_generator.rb",
     "init.rb",
     "lib/forgery.rb",
     "lib/forgery/dictionaries.rb",
     "lib/forgery/dictionaries/cities",
     "lib/forgery/dictionaries/colors",
     "lib/forgery/dictionaries/company_names",
     "lib/forgery/dictionaries/countries",
     "lib/forgery/dictionaries/female_first_names",
     "lib/forgery/dictionaries/frequencies",
     "lib/forgery/dictionaries/genders",
     "lib/forgery/dictionaries/languages",
     "lib/forgery/dictionaries/last_names",
     "lib/forgery/dictionaries/lorem_ipsum",
     "lib/forgery/dictionaries/male_first_names",
     "lib/forgery/dictionaries/name_suffixes",
     "lib/forgery/dictionaries/name_titles",
     "lib/forgery/dictionaries/province_abbrevs",
     "lib/forgery/dictionaries/provinces",
     "lib/forgery/dictionaries/races",
     "lib/forgery/dictionaries/shirt_sizes",
     "lib/forgery/dictionaries/state_abbrevs",
     "lib/forgery/dictionaries/states",
     "lib/forgery/dictionaries/street_suffixes",
     "lib/forgery/dictionaries/streets",
     "lib/forgery/dictionaries/top_level_domains",
     "lib/forgery/extensions/array.rb",
     "lib/forgery/extensions/hash.rb",
     "lib/forgery/extensions/range.rb",
     "lib/forgery/extensions/string.rb",
     "lib/forgery/file_reader.rb",
     "lib/forgery/forgery.rb",
     "lib/forgery/forgery/address.rb",
     "lib/forgery/forgery/basic.rb",
     "lib/forgery/forgery/internet.rb",
     "lib/forgery/forgery/lorem_ipsum.rb",
     "lib/forgery/forgery/monetary.rb",
     "lib/forgery/forgery/name.rb",
     "lib/forgery/forgery/personal.rb",
     "lib/forgery/forgery_api.rb",
     "lib/forgery/formats.rb",
     "lib/forgery/formats/phone",
     "lib/forgery/formats/street_number",
     "lib/forgery/formats/zip",
     "spec/dictionaries_spec.rb",
     "spec/extensions/array_spec.rb",
     "spec/extensions/range_spec.rb",
     "spec/extensions/string_spec.rb",
     "spec/file_reader_spec.rb",
     "spec/forgery/address_spec.rb",
     "spec/forgery/basic_spec.rb",
     "spec/forgery/internet_spec.rb",
     "spec/forgery/lorem_ipsum_spec.rb",
     "spec/forgery/monetary_spec.rb",
     "spec/forgery/name_spec.rb",
     "spec/forgery/personal_spec.rb",
     "spec/forgery_spec.rb",
     "spec/formats_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/sevenwire/forgery}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Easy and customizable generation of forged data.}
  s.test_files = [
    "spec/dictionaries_spec.rb",
     "spec/extensions/array_spec.rb",
     "spec/extensions/range_spec.rb",
     "spec/extensions/string_spec.rb",
     "spec/file_reader_spec.rb",
     "spec/forgery/address_spec.rb",
     "spec/forgery/basic_spec.rb",
     "spec/forgery/internet_spec.rb",
     "spec/forgery/lorem_ipsum_spec.rb",
     "spec/forgery/monetary_spec.rb",
     "spec/forgery/name_spec.rb",
     "spec/forgery/personal_spec.rb",
     "spec/forgery_spec.rb",
     "spec/formats_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

